const env = {
  AWS_VAR_ACCESS_KEY: process.env.NEXT_PUBLIC_AWS_VAR_ACCESS_KEY!,
  AWS_VAR_SECRET_ACCESS_KEY: process.env.NEXT_PUBLIC_AWS_VAR_SECRET_ACCESS_KEY!,
  SKARTNER_AI: process.env.NEXT_PUBLIC_SKARTNER_AI!,
};
export default env;
